project:
  type: website
  output-dir: docs

website:
  title: "Volt Typhoon Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: detection_sources.qmd
        text: Detection Sources
      - href: mitigation_coverage.qmd
        text: Mitigation Coverage
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true